name: flutter_todos
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  uuid: ^4.5.1
  meta: ^1.16.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  go_router: ^16.0.0
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/splash/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/splash/splash_logo.png # Center logo image
  # branding: assets/splash/splash_branding.png # Optional footer logo (optional)
  color_dark: "#000000" # Dark mode background
  image_dark: assets/splash/splash_logo.png # Dark mode logo (optional)
  # branding_dark: assets/splash/splash_branding.png # Dark mode footer logo (optional)

  android_12:
    image: assets/splash/splash_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash/splash_logo.png
    icon_background_color_dark: "#000000"

  web: false # optional; set to true if you want web splash too

  android: true
  ios: true
